name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    name: 'Testing'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13', '1.12' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1.1.2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go vet github.com/asyncapi/parser-go/cmd/api-parser
          go list ${PWD}/... | xargs -L1 go test

  release:
    name: 'Release to GitHub'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: asyncapi-bot
          GIT_AUTHOR_EMAIL: info@asyncapi.io
          GIT_COMMITTER_NAME: asyncapi-bot
          GIT_COMMITTER_EMAIL: info@asyncapi.io
        run: npx semantic-release
